# Ultralytics YOLO 🚀, AGPL-3.0 license

# Parameters
nc: 80
scales:
  n: [0.33, 0.25, 1024]

backbone:
  # [from, repeats, module, args]
  - [-1, 1, GFFP, []]
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 3, C2f_FPEUs, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 6, C2f_FPEUs, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]
  - [-1, 6, C2f_FPEUs, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]
  - [-1, 3, C2f_FPEUs, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]

head:
  - [ -1, 1, nn.Upsample, [ None, 2, "nearest" ] ]
  - [ [ -1, 7 ], 1, Concat, [ 1 ] ]
  - [ -1, 3, C2f, [ 512 ] ]

  - [ -1, 1, nn.Upsample, [ None, 2, "nearest" ] ]
  - [ [ -1, 5 ], 1, Concat, [ 1 ] ]
  - [ -1, 3, C2f, [ 256 ] ]

  - [ -1, 1, Conv, [ 256, 3, 2 ] ]
  - [ [ -1, 13 ], 1, Concat, [ 1 ] ]
  - [ -1, 3, C2f, [ 512 ] ]

  - [ -1, 1, Conv, [ 512, 3, 2 ] ]
  - [ [ -1, 10 ], 1, Concat, [ 1 ] ]
  - [ -1, 3, C2f, [ 1024 ] ]

  - [ [ 16, 19, 22 ], 1, Detect, [ nc ] ]





